%JDSY 01-25-2011
%%% Initilazation script for He4 system
close all;
clear all;
instrreset;

global smdata; 
global smscan;
 
%Load rack
if 1==1
  %note rack is generated by "He4RackCreationScript"
  load('He4-Rack_01-Feb-2011.mat');
end

%% Intialization Settings
UseCryoMag = 1;
TwoLockin = 1; 
KeithleyVoltage = 1; %0 for current source (and T), 1 for voltage source (and gating) 

%% GPIB addresses for machines
k2400adr = 14;
k2700adr = 16;
sr830adr = 8;
MagContadr = 1;
Sr830_top_adr = 9;

%% Retrieve instrument indices and open connection to machines
sminstlookup('LowerLockin');
sr830ind = sminstlookup('LowerLockin');
k2400ind = sminstlookup('K2400V');
k2700ind = sminstlookup('DMM');
dacind = sminstlookup('DecaDAC');
k2400indT = sminstlookup('K2400T');
MagContind = sminstlookup('MagnetController');
sr830topind = sminstlookup('UpperLockin');

smdata.inst(sr830ind).data.inst = gpib('ni', 0, sr830adr);
smdata.inst(k2400ind).data.inst = gpib('ni', 0, k2400adr);
smdata.inst(k2700ind).data.inst = gpib('ni', 0, k2700adr);
smdata.inst(dacind).data.inst = serial('COM5');
if UseCryoMag == 1
    smdata.inst(MagContind).data.inst = gpib('ni', 0, MagContadr);
end
if TwoLockin == 1
    smdata.inst(sr830topind).data.inst = gpib('ni', 0, Sr830_top_adr);
end

fopen(smdata.inst(sr830ind).data.inst);
fopen(smdata.inst(k2400ind).data.inst);
fopen(smdata.inst(k2700ind).data.inst);
fopen(smdata.inst(dacind).data.inst);
if UseCryoMag == 1
    fopen(smdata.inst(MagContind).data.inst);
end
if TwoLockin == 1
    fopen(smdata.inst(sr830topind).data.inst);
end

%% Keithley 2400 is intialized differently as voltage source or for
%%% temperature measurement
if KeithleyVoltage == 1
    %initialize the Keithley 2400 as a voltage source
    fprintf(smdata.inst(k2400ind).data.inst,'*RST');
    fprintf(smdata.inst(k2400ind).data.inst,':sour:func volt');
    fprintf(smdata.inst(k2400ind).data.inst,':sour:volt:mode fix');
    fprintf(smdata.inst(k2400ind).data.inst,':sour:volt:rang 200');
    fprintf(smdata.inst(k2400ind).data.inst,':sens:curr:prot 10e-6');
    fprintf(smdata.inst(k2400ind).data.inst,':sens:curr:RANG 10e-6');
    fprintf(smdata.inst(k2400ind).data.inst,':outp on');
else
    %initialize Keithley 2400 as a current source (for reading T or driving
    %magnet)
    fprintf(smdata.inst(3).data.inst,'*RST');
    fprintf(smdata.inst(3).data.inst,':sour:func curr');
    fprintf(smdata.inst(3).data.inst,':sens:func "volt"');
    fprintf(smdata.inst(3).data.inst,':outp on');
    fprintf(smdata.inst(3).data.inst,':sour:curr -1e-5')
end

%% initialize the magnet
if UseCryoMag == 0
    fprintf(smdata.inst(MagContind).data.inst,'UNITS T');
    %fprintf(smdata.inst(MagContind).data.inst,'RANGE 0 0.2');
    %fprintf(smdata.inst(MagContind).data.inst,'RATE 0 0.02');
end


LoadSensorCal;
smdata.inst(k2400indT).data.inst = smdata.inst(k2400ind).data.inst;
smgui;

cd('Z:\group\Topological Insulator\Samples\Thin Film Samples Valla\VF_series2\S2G4XY\YA_split_gate1\');
%load('C:\Special_Measure\Measurement Setups\He4 Setup\He4 Example Scans\smscan_BG');

